### ISSUE TITLE
[Bug] Is there something wrong with the JNCEP? "Unrecoverable error"

### ISSUE THREAD

**Issue by LostOnTheLine** [Nitrousoxide/jncep-docker-build#2]
I keep getting the error
```
*** ❌ An unrecoverable error occured ***
All connection attempts failed
```
I've checked & attempted to update my credentials, I've tried running the script pieces independently
```
jncep $@ update -w #-v --email "myemail@**#REDACTED#**.com" --password "**#REDACTED#**"
```
gives the same error

```
jncep $@ update -w -v --email myemail@#REDACTED#.com --password #REDACTED#
```
same error

It worked a week ago without issue & I do not believe anything changed. I checked the other JNCEP repos & I do not see any updates about an issue but cannot get it to work

**Comment by Nitrousoxide** [comment]
Did you already set the env variables in the compose file when you deployed the container?  If so there's no need to define them again when running the command.

If they are already defined as env variable just run 
jncep $@ update -w

**Comment by LostOnTheLine** [comment]
It was working fine. I ran it exactly as I did previously & got that response, Using the manually defined credentials was part my attempts to get it to work but it doesn't run with or without them.

**Comment by LostOnTheLine** [comment]
I just tried running it again & it worked this time. I guess it was an issue either with my local environment or the system that resolved by using the "come back & try again in an hour" method
